---
title: "Country heatmap"
author: "Michael Beer"
output: html_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library("ggplot2")
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library(rgeos)
theme_set(theme_void())
suicides <- read_csv("../data/master.csv")
```

```{r suicide}
suicides_clean <- suicides %>% 
  rename(hdi = 'HDI for year',
         suicides_per_100k_pop = 'suicides/100k pop',
         country_year = 'country-year',
         gdp ='gdp_for_year ($)',
         gdp_per_capita = 'gdp_per_capita ($)') 
```

```{r suicide-average}
suicide_rates <- suicides_clean %>%
  group_by(country) %>% 
  summarise(suicide_rates = mean(suicides_per_100k_pop)) %>% 
  arrange(desc(suicide_rates))
```

```{r world}
world <- ne_countries(scale = "medium", returnclass = "sf") %>%
  filter(type == "Sovereign country" | type == "Country")
world_points <- st_centroid(world)
world_points <- cbind(world, st_coordinates(st_centroid(world$geometry)))
```

```{r total-suicides-country-per-pop}
  suicide_heat <- suicide_rates %>%
  rename(name_long = 'country')
```

```{r world-map-suicides}
  suicidemap <- merge(world, suicide_heat, by="name_long", all=TRUE)
```

```{r heatmap}
  worldheat <- ggplot(data = suicidemap) +
    geom_sf(aes(fill = suicide_rates)) +
        labs(title = "Suicide Rates Per Country", fill = "Suicide Rates Per \n 100k People") +
           scale_fill_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="grey") +
                            theme(panel.background = element_rect(fill = "ivory", color = "black"))
  worldheat

```

```{r europe}
worldheat +
  coord_sf(xlim = c(-30, 60), ylim = c(30, 80), expand = FALSE) +
  labs(title = "Suicide Rates Per Country (Europe)")
```

```{r southamerica}
worldheat +
  coord_sf(xlim = c(-90, -30), ylim = c(-60, 15), expand = FALSE) +
  geom_text(data= world_points,aes(x=X, y=Y, label=name),
    color = "black", check_overlap = TRUE) +
      labs(title = "Suicide Rates Per Country (South America)")
```