---
title: "HDI impact on suicides"
autor: "Fernando Gomes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
suicides <- read_csv("../data/master.csv")
library(tidyverse)
library(tidymodels)
library(openintro)
library(patchwork)
```

```{r suicide}
suicides_clean <- suicides %>% 
  rename(hdi = 'HDI for year',
         suicides_per_100k_pop = 'suicides/100k pop',
         country_year = 'country-year',
         gdp ='gdp_for_year ($)',
         gdp_per_capita = 'gdp_per_capita ($)') 
```

```{r suicide-average}
suicide_rates_hdi <- suicides_clean %>%
  filter(!is.na(hdi)) %>%
  group_by(country) %>%
  summarise(suicide_rates = mean(suicides_per_100k_pop), mean_hdi = mean(hdi)) %>% 
  arrange(desc(suicide_rates))
  
suicide_rates_hdi
```

```{r}
suicide_rates_hdi %>%
  ggplot(aes(x = mean_hdi, y = suicide_rates)) + 
  geom_point() +
  geom_smooth(method = "lm", color = "red") +
  labs(title = "Rate of Suicides Against HDI",
       x = "Human Development Index",
       y = "Suicides per 100k Population")
``` 

```{r linear model}
HDI_suicides_reg <- linear_reg() %>% 
  set_engine("lm") %>% 
  fit(suicide_rates ~ mean_hdi, data = suicide_rates_hdi)
tidy(HDI_suicides_reg)
```

The linear model shows that for every 0.1 increase in HDI there is an increase of 2.26 in the average suicides per 100000 people. This trend is opposite to what we predicted as we suspected an increase in HDI would lower suicide rates.

The formula for this linear model is:
Average Suicides per 100k pop = -5.69 + 22.6 * Mean HDI


